name: Release
on:
  push:
    tags:
      - '*'
env:
  SPIGOT_VERSION: 1.19
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Cache BuildTools.jar
        id: cache-buildtools
        uses: actions/cache@v3
        with:
          path: ./server/BuildTools.jar
          key: buildtools
      - name: Download BuildTools.jar
        if: steps.cache-buildtools.outputs.cache-hit != 'true'
        run: wget -O ./server/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Cache Spiogt
        id: cache-spigot
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: spigot-${{ env.SPIGOT_VERSION }}
      - name: Initialize repositories
        if: steps.cache-spigot.outputs.cache-hit != 'true'
        run: java -jar BuildTools.jar --rev ${{ env.SPIGOT_VERSION }}
        working-directory: ./server
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ./build/libs/*.jar
